# -*- coding: utf-8 -*-
"""Customer Churn Prediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ggaQI8un_VZP1wPUX1GA0vkazhZNj5dN
"""

import pandas as pd

df=pd.read_csv("/content/WA_Fn-UseC_-Telco-Customer-Churn.csv")

df.head()

df.info()

df.columns

df.describe()

df.fillna(0, inplace=True)

df.isnull().sum()

df.duplicated()

df.drop_duplicates(inplace=True)

df.duplicated().sum()

import seaborn as sns
import matplotlib.pyplot as plt

df["Churn"].value_counts()

sns.countplot(x='Churn', data=df)
plt.title('Customers Who Churned vs Stayed')
plt.show()

df["MonthlyCharges"].hist(bins=30)
plt.title('Monthly Charges Distribution')
plt.show()

df.corr(numeric_only=True)

sns.heatmap(df.corr(numeric_only=True))
plt.title('Correlation Heatmap')
plt.show()

df.boxplot(column='MonthlyCharges')
plt.title('Monthly Charges Distribution by Churn')
plt.show()

Q1 = df['MonthlyCharges'].quantile(0.25)
Q3 = df['MonthlyCharges'].quantile(0.75)
IQR = Q3 - Q1
lower=Q1 - 1.5*IQR
upper=Q3 + 1.5*IQR
df = df[(df['MonthlyCharges'] >= lower) &
(df['MonthlyCharges'] <= upper)]
print(lower)
print(upper)

from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

df["gender"]=le.fit_transform(df["gender"])
df["Churn"]=le.fit_transform(df["Churn"])

df["gender"]

df["Churn"]

df=pd.get_dummies(df,columns=["Partner","Dependents","PhoneService","MultipleLines","InternetService","OnlineSecurity","OnlineBackup","DeviceProtection","TechSupport","StreamingTV","StreamingMovies","Contract","PaperlessBilling","PaymentMethod"])

df.head()

from sklearn.preprocessing import StandardScaler

df["tenure"]

scalar=StandardScaler()
df['TotalCharges'].fillna(0, inplace=True)
df[['MonthlyCharges','TotalCharges']]=scalar.fit_transform(df[['MonthlyCharges','TotalCharges']])

df[["MonthlyCharges","TotalCharges"]]

from sklearn.model_selection import train_test_split

df["Churn"]=df["Churn"].astype(int)

x=df.drop(["Churn", "customerID"],axis=1)
y=df["Churn"]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(max_iter=1000)

LogReg=lr.fit(x_train,y_train)

from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(random_state=42)

RandomForest=rf.fit(x_train,y_train)

from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()

DecTree=dt.fit(x_train,y_train)

from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()

KNN=knn.fit(x_train,y_train)

from sklearn.metrics import (accuracy_score,confusion_matrix)
print("Logistic Regression")
print(accuracy_score(y_test,LogReg.predict(x_test)))
print(confusion_matrix(y_test,LogReg.predict(x_test)))
print("Random Forest Classifier")
print(accuracy_score(y_test,RandomForest.predict(x_test)))
print(confusion_matrix(y_test,RandomForest.predict(x_test)))
print("Decision Tree")
print(accuracy_score(y_test,DecTree.predict(x_test)))
print(confusion_matrix(y_test,DecTree.predict(x_test)))
print("KNN")
print(accuracy_score(y_test,KNN.predict(x_test)))
print(confusion_matrix(y_test,KNN.predict(x_test)))

from sklearn.metrics import (accuracy_score,confusion_matrix)
print("Logistic Regression")
print(accuracy_score(y_test,LogReg.predict(x_test)))
print(confusion_matrix(y_test,LogReg.predict(x_test)))
print("Random Forest Classifier")
print(accuracy_score(y_test,RandomForest.predict(x_test)))
print(confusion_matrix(y_test,RandomForest.predict(x_test)))
print("Decision Tree")
print(accuracy_score(y_test,DecTree.predict(x_test)))
print(confusion_matrix(y_test,DecTree.predict(x_test)))
print("KNN")
print(accuracy_score(y_test,KNN.predict(x_test)))
print(confusion_matrix(y_test,KNN.predict(x_test)))

lr_acc=accuracy_score(y_test,LogReg.predict(x_test))
rf_acc=accuracy_score(y_test,RandomForest.predict(x_test))
dt_acc=accuracy_score(y_test,DecTree.predict(x_test))
knn_acc=accuracy_score(y_test,KNN.predict(x_test))

accuracies=[lr_acc,rf_acc,dt_acc,knn_acc]
models=["Logistic Regression","Random Forest Classifier","Decision Tree","KNN"]
best=max(accuracies)
best_index=accuracies.index(best)
print("The best model is ",models[best_index])

import joblib
joblib.dump(lr, "lr_model.pkl")
joblib.dump(df.head(), "df_head.pkl")

